# Generated by Django 3.2.5 on 2023-04-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipoint', '0002_paystackmodel_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystackmodel',
            name='cache_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
