# Generated by Django 3.2.5 on 2023-04-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipoint', '0003_paystackmodel_cache_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackmodel',
            name='account',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
