# Generated by Django 3.2.5 on 2023-03-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMgt', '0002_auto_20230302_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('suite', models.CharField(blank=True, max_length=30, null=True)),
                ('zip', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('same_ship', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
