# Generated by Django 3.2.5 on 2023-03-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userMgt', '0004_auto_20230306_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='adrress_choice',
            new_name='address_choice',
        ),
    ]
