# Generated by Django 3.2.5 on 2023-04-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parizian', '0006_auto_20230420_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
