# Generated by Django 3.2.5 on 2023-04-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parizian', '0007_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
