# Generated by Django 3.2.5 on 2023-04-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parizian', '0008_item_has_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='coupon',
        ),
        migrations.AddField(
            model_name='coupon',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parizian.coupon'),
        ),
    ]
