# Generated by Django 3.2.5 on 2023-04-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parizian', '0009_auto_20230420_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_coupon', to='parizian.coupon'),
        ),
    ]
