# Generated by Django 3.2.5 on 2023-04-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parizian', '0011_alter_coupon_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='create_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
