# Generated by Django 3.2.5 on 2023-02-24 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=50, verbose_name='business name')),
                ('reg_no', models.CharField(max_length=50, verbose_name='business registration number')),
            ],
        ),
    ]
